### ISSUE TITLE
Host as website

### ISSUE THREAD

**Issue by koppor** [SixArm/sixarm_ruby_markdown_table_of_contents#2]
I would love to have a web site, where I can paste my markdown and the TOC of the markdown is then updated. Would it be possible to host such a service?

Reason: That would open this service to a more broader user base.

**Comment by joelparkerhenderson** [comment]
Do you mean essentially one web page, with a big text area, where you paste markdown text, then the page shows you the result?

Or do you mean something more advanced, more akin to a blog hosting site, or static site generator, or webhook updater?

**Comment by koppor** [comment]
I mean the first point. 😇 Example URL: http://www.sixarm.com/markdown-toc-generator. This would really enough for me. The focus is on manual update of markdown files. The automation thing of second idea can be achieved by programming something or writing a Jekyll plugin.

**Comment by joelparkerhenderson** [comment]
Ok. So if I understand you correctly, the underlying implementation doesn't matter for this? 

I.e. to solve what you're asking, the underlying implementation could use something akin to CGI that calls the existing Ruby gem, or could use something akin to a web page that calls some JavaScript implementation. Yes?

**Comment by koppor** [comment]
Yeah - no requirements on the implementation :-). Assuming that it runs in a sandbox and cannot escape due to malformed Markdown or whatever intrusion ideas are there around. - On the one hand, I was hoping that it can be simple done adding a wrapper around the script without the need to reimplement it in JavaScript. On the other hand, a JavaScript (TypeScript?) library would allow it being reused in other (web-?)projects and even make it more attractive 😺 .

**Comment by joelparkerhenderson** [comment]
I like your idea of usability in more projects.

I will try porting to JavaScript in general and to Node specifically: https://github.com/sixarm/sixarm_node_markdown_table_of_contents

If the porting succeeds, then it should be really easy to upgrade the code to TypeScript too.

**Comment by koppor** [comment]
Thank you for the effort! I starred the other repo and hope there will a `gh-pages` branch soon 😇 .

**Comment by koppor** [comment]
Bump. 😇 

I was reading https://github.com/cirosantilli/essays/tree/59adcc6dcd0b16430fe97495aa5b98707abc53d8#moving-from-markdown-to-asciidoc and thought "TOC is solved by https://github.com/SixArm/sixarm_ruby_markdown_table_of_contents/". I wanted to comment and point to an online website having it even more easy. However, I found that there is none ^^. With the other repo, it should be easy to host it as gh-pages, isn't it?

**Comment by koppor** [comment]
I am currently editing a markdown file in the browser with a TOC. Just wanted to use an online service for that. Is there any chance that https://github.com/joelparkerhenderson/sixarm_node_markdown_table_of_contents will be accessible at a web site (SaaS 👍 ).
